### PR TITLE
add dev tool to plugin

### PR DESCRIPTION
**Pull request by digitalsadhu**
Automatically adds the Podium dev tool whenever the app is in development mode

### CODE REVIEW

**Comment by trygve-lie** [comment]
I am a bit unsure on this to be honest. My biggest worry is on the topic to pull a full devtool into here when the app are in production. What dependencies will this pull in in production?

**Comment by digitalsadhu** [comment]
Ah yea thats true, while it wont run the dev tool at all in prod it will pull in the dev tool as a dep. I could move it to dev deps though?

**Comment by trygve-lie** [comment]
@digitalsadhu What did we conclude with here?

**Comment by digitalsadhu** [comment]
Drop it. Only a few lines of code.

**Pull request closed without merging**
